### ISSUE TITLE
Unknown file URLs for danbooru

### ISSUE THREAD

**Issue by Sunako** [xeron/danbooru-ruby-grabber#11]
As the above title says, this is mostly regarding banned artists, but also affects some other tags where I believe the API for danbooru doesn't give any image URL result. Would it be possible to fix this by grabbing the md5 from the API for a blocked post? Because if so the file URL is just that plus the file extension.

As an example here is a post from a banned artist: https://danbooru.donmai.us/posts/2438399 and the file url is just /data/5fd14d16134e9698fb1d7eeeadc2b81f.jpg.  Alternatively I have no idea how you feel about this, but if you just look at the page HTML for a blocked post the "data-file-url" element contains the file URL as well which maybe you can use.

**Comment by xeron** [comment]
This is what I see from the API for this post:

```json
{
  "id": 2438399,
  "created_at": "2016-07-30T08:26:57.531-04:00",
  "uploader_id": 15864,
  "score": 23,
  "source": "http://i4.pixiv.net/img-original/img/2016/07/25/00/40/20/58074319_p0.jpg",
  "last_comment_bumped_at": null,
  "rating": "s",
  "image_width": 703,
  "image_height": 1000,
  "tag_string": "1girl banned_artist blush boots cherry_blossoms cross-laced_footwear flower hair_ribbon japanese_clothes kamikaze_(kantai_collection) kantai_collection konomi_(kino_konomi) lace-up_boots long_hair looking_at_viewer meiji_schoolgirl_uniform petals pink_hakama purple_eyes purple_hair ribbon solo yellow_ribbon",
  "is_note_locked": false,
  "fav_count": 15,
  "last_noted_at": null,
  "is_rating_locked": false,
  "parent_id": null,
  "has_children": false,
  "approver_id": null,
  "tag_count_general": 19,
  "tag_count_artist": 2,
  "tag_count_character": 1,
  "tag_count_copyright": 1,
  "file_size": 650674,
  "is_status_locked": false,
  "fav_string": "fav:448873 fav:61585 fav:106800 fav:469777 fav:19831 fav:60223 fav:196099 fav:423018 fav:393097 fav:12146 fav:459949 fav:388687 fav:15864 fav:431891 fav:481431",
  "pool_string": "",
  "up_score": 23,
  "down_score": 0,
  "is_pending": false,
  "is_flagged": false,
  "is_deleted": false,
  "tag_count": 23,
  "updated_at": "2016-07-30T08:26:57.531-04:00",
  "is_banned": true,
  "pixiv_id": 58074319,
  "last_commented_at": null,
  "has_active_children": false,
  "bit_flags": 0,
  "uploader_name": "Magus",
  "has_large": false,
  "tag_string_artist": "banned_artist konomi_(kino_konomi)",
  "tag_string_character": "kamikaze_(kantai_collection)",
  "tag_string_copyright": "kantai_collection",
  "tag_string_general": "1girl blush boots cherry_blossoms cross-laced_footwear flower hair_ribbon japanese_clothes lace-up_boots long_hair looking_at_viewer meiji_schoolgirl_uniform petals pink_hakama purple_eyes purple_hair ribbon solo yellow_ribbon",
  "has_visible_children": false
}
```

No `md5`, no urls except `source` which returns `403` (probably protected by referer, but may be something more complicated).

**Comment by Sunako** [comment]
Hm, that is unfortunate that the API doesn't return anything useful. Maybe I will make some extra script to record the output and scrape the HTML for blocked post URL to download.

Oh well, thanks anyway.

**Comment by xeron** [comment]
@Sunako see https://github.com/xeron/danbooru-ruby-grabber/pull/12. Currently testing.

**Comment by Sunako** [comment]
Oh wow nice, I will give it a try on a few things and edit this post with results.
