### ISSUE TITLE
Cannot download images when the tag has ampersand and semicolon

### ISSUE THREAD

**Issue by dyskette** [xeron/danbooru-ruby-grabber#13]
Examples:
```
ruby danbooru.rb -b konachan -d ~/Pictures 'allison_&_lillia'
ruby danbooru.rb -b konachan -d ~/Pictures 'robotics;notes'
```
These create a folder with the tag, the file `files.bbs` inside, and exits.

**Comment by xeron** [comment]
@dyskette thank you for reporting this! Should be fixed now.

The problem was related to usage of ruby's `URI.escape` which is actually deprecated and doesn't follow RFC. I removed it completely and now using `CGI.escape` to encode parameters.

**Comment by dyskette** [comment]
Right, thank you.

The escaping is fixed, and now those tags work. However, now it just takes one tag. If I put 2 or more, it prints the tags in the terminal, creates the folder (with bbs file inside) and exits.

**Comment by xeron** [comment]
Oh shi~

So I should escape everything except `+` because they use `+` for tags separation.

**Comment by xeron** [comment]
Fixed in https://github.com/xeron/danbooru-ruby-grabber/pull/16.

**Comment by dyskette** [comment]
Confirmed, it works OK now. Thanks.
