### ISSUE TITLE
Failed download resume handling question

### ISSUE THREAD

**Issue by dasbootbee** [xeron/danbooru-ruby-grabber#24]
Downloading a large set of images (3000+) and hit a connection timeout.  When I run the same command again to download, it starts redownloading all files (overwriting files already downloaded).  The previously downloaded files appear in files.bbs.  

Am I missing an argument to tell it to skip previously downloaded files?

Using defaults:

`./danbooru.rb -b yandere -u userid -p password tag`

**Comment by xeron** [comment]
No it should check and skip the download for existing files which have the same MD5 checksum.

e.g.:

```
$ bundle exec ruby danbooru.rb -b yandere touhou
Tags are touhou.
Page 1/289:
Saving touhou/886060.png... (1/28865)
saved!
Saving touhou/885955.png... (2/28865)
saved!
Saving touhou/885952.png... (3/28865)
^C
```

then restart download:

$ bundle exec ruby danbooru.rb -b yandere touhou
Tags are touhou.
Page 1/289:
File exists - touhou/886060.png (1/28865)
File exists - touhou/885955.png (2/28865)
Saving touhou/885952.png... (3/28865)
saved!
```

**Comment by dasbootbee** [comment]
Thanks for the reply.

I'm a total Ruby noob (nuby?) and I assumed I could just run danbooru.rb from the terminal once I had Ruby installed.  Is that not the case?  

I tried your command and it said I needed to run bundle install first.  I did but one of the dependencies fails (filemagic).  I looked on their bug tracker and it straight up says they're not maintaining it for Windows anymore.  Am I hosed?

Thanks for putting up with my ignorance.

**Comment by xeron** [comment]
You don't have to use `bundle exec` as long as you have required dependencies installed using `gem install` which I think is the case since you've already run this tool before.

As for your original problem:

Script doesn't use `files.bbs` to check existing files. What it does is:

1. fetches file information from the image board
2. checks if file exists by the file name
3. if file exists it compares MD5 sum from the data with an actual file MD5 sum
4. if sum is the same it skips download
5. otherwise it downloads the file

I never tested this on Windows tho.

**Comment by dasbootbee** [comment]
Thanks for the info.  Unfortunately the filemagic gem will not compile on Windows and they developers don't seem to want to fix it.  I'll close this out since it seems to be an upstream issue.

**Comment by xeron** [comment]
As I said you don't need `filemagic` to run this tool. It's only needed to run tests when using bundler.

Your method of running the tool using `danbooru.rb -b yandere -u userid -p password tag` is fine.

You can try this is you want:

```
danbooru.rb -b yandere touhou
```

download 5-6 images and press Ctrl+C, then repeat:

```
danbooru.rb -b yandere touhou
```

and check if it says "File exists" for these files.
